email_hse = {1: "Нет данных",
             2: "aagilinskaya@edu.hse.ru",
             3: "vigrishkina@edu.hse.ru",
             4: "kaeritsyan@edu.hse.ru",
             5: "avkaprielov@edu.hse.ru",
             6: "ssmanzhilevskiy@edu.hse.ru",
             7: "yavmiklukho@edu.hse.ru",
             8: "aanazaretyan@edu.hse.ru",
             9: "oknalivayko@edu.hse.ru",
             10: "edpavlova_1@edu.hse.ru",
             11: "kipashina@edu.hse.ru",
             12: "essavchuk@edu.hse.ru",
             13: "rrsaykov_1@edu.hse.ru",
             14: "oesenyukova@edu.hse.ru",
             15: "ayusmirnov_2@edu.hse.ru",
             16: "adtoropov@edu.hse.ru",
             17: "oefonareva@edu.hse.ru",
             18: "afkhabibova@edu.hse.ru",
             19: "edchevkin@edu.hse.ru",
             20: "mdchibrin@edu.hse.ru",
             21: "asheripbaev@edu.hse.ru",
             22: "aiyufanov@edu.hse.ru",
             23: "nsyarygin@edu.hse.ru"
             }

email_miem = {1: "Нет данных",
             2: "aagilinskaya@miem.hse.ru",
             3: "vigrishkina@miem.hse.ru",
             4: "kaeritsyan@miem.hse.ru",
             5: "avkaprielov@miem.hse.ru",
             6: "ssmanzhilevskiy@miem.hse.ru",
             7: "yavmiklukho@miem.hse.ru",
             8: "aanazaretyan@miem.hse.ru",
             9: "oknalivayko@miem.hse.ru",
             10: "edpavlova_1@miem.hse.ru",
             11: "kipashina@miem.hse.ru",
             12: "essavchuk@miem.hse.ru",
             13: "rrsaykov_1@miem.hse.ru",
             14: "oesenyukova@miem.hse.ru",
             15: "ayusmirnov_2@miem.hse.ru",
             16: "adtoropov@miem.hse.ru",
             17: "oefonareva@miem.hse.ru",
             18: "afkhabibova@miem.hse.ru",
             19: "edchevkin@miem.hse.ru",
             20: "mdchibrin@miem.hse.ru",
             21: "asheripbaev@miem.hse.ru",
             22: "aiyufanov@miem.hse.ru",
             23: "nsyarygin@miem.hse.ru"
             }

vk = {1: "https://vk.com/id575060335",
             2: "https://vk.com/whatdomakeyouloveme",
             3: "https://vk.com/id326548082",
             4: "https://vk.com/id77375402",
             5: "https://vk.com/shurik_ka",
             6: "https://vk.com/claba",
             7: "https://vk.com/y_mikluho",
             8: "https://vk.com/alfaxa4",
             9: "https://vk.com/luntra",
             10: "https://vk.com/elenapavlova12312",
             11: "https://vk.com/shivireva",
             12: "https://vk.com/id107873017",
             13: "https://vk.com/robertinosad",
             14: "https://vk.com/id296109825",
             15: "https://vk.com/smalyu",
             16: "https://vk.com/ice_6cream",
             17: "https://vk.com/nomerid1",
             18: "https://vk.com/id121592605",
             19: "https://vk.com/echevkin",
             20: "https://vk.com/michibrin",
             21: "https://vk.com/ask_hyu",
             22: "https://vk.com/ayufanov",
             23: "https://vk.com/mashina101"
             }
